# fly.toml app configuration file generated for ladsfantasyfootball on 2026-09-17T17:54:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ladsfantasyfootball'
primary_region = 'ord'

[build]

[env]
  AUTO_SYNC = 'true'
  AUTO_SYNC_MINUTES = '180'
  DB_PATH = '/data/league.db'
  NODE_ENV = 'production'
  SLEEPER_LEAGUE_ID = '1386530997679443968,1254525039957516288'

[[mounts]]
  source = 'lads_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
